### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by jonathon-love** [vjalby/multipleresponse#2]
This is looking great!

1. you could do away with the duplicate "Multiple Response" heading

<img width="236" alt="Screenshot 2023-11-02 at 20 43 12" src="https://github.com/vjalby/multipleresponse/assets/3240247/72d50683-164c-446d-8b27-9026e0c5465b">

you've bound `rows` to `resps`

https://github.com/vjalby/multipleresponse/blob/main/MultipleResponse/jamovi/multipleresponse.r.yaml#L14

but you actually want rows+1 ... the way you've currently got it, you're adding the total row in the .run() phase, and so everytime a change is made to the analysis, it bounces up and down. in this case, ditch the data-binding and define a function `.init()` alongside `.run()`, and do something like:

```
.init=function() {
    for (v in self$options$resps) {
        self$results$responses$addRow(rowKey=v)
    }
    if (self$options$total)
        self$results$responses$addRow(rowKey='.total')
}
```

by setting the correct number of rows in the .init() phase, you avoid that bouncing up and down effect.

otherwise, this looks great!

**Comment by vjalby** [comment]
Jonothon,

Sorry for this late reply... I changed my mac for the new M3 and it took some time to be up and ready again :)

of course, I've included your two suggestions. For the second, I kept `reps` bounded to `rows` but added the total row in the `.init()` instead of `.run()` to prevent bouncing as you suggested.

I also managed to give a 'result' (table and plot) even if there's only 1 active variable. 

I will wait a bit to keep testing it, then I will submit it to be included in Jamovi library if you think it deserves it.

Thanks for your help !

**Comment by hyunsooseol** [comment]
Hi [vjalby](https://github.com/vjalby)

Recently, when I try to install moretest module in jamovi library, I can not find multiple response module within moretest module in jamovi on WIN 10.
Could you check it for me please? Thanks in advance.

Best Regards
Seol

**Comment by vjalby** [comment]
Hi @hyunsooseol 

Sorry for this very very late answer. My module "MultipleResponse" is not part of MoreTest module. it's actually not yet available in official Jamovi Library. But I should release it very soon.

Best,

Vincent

**Comment by hyunsooseol** [comment]
Hi [vjalby](https://github.com/vjalby)

When do I expect to release the module?

Thanks.

Sincerely
Seol

**Comment by vjalby** [comment]
Jonathon asked me for a few changes. I will asap (2 or 3 weeks...)

**Comment by hyunsooseol** [comment]
Hi [vjalby](https://github.com/vjalby)

When do I expect to release the module?

I want to use it in class. 

Kind
Seol

**Comment by vjalby** [comment]
Hi. I'm just back from a trip for work. I will send it to Jonathon this week ! Sorry for the delay

**Comment by vjalby** [comment]
@hyunsooseol 

The module is now available in jamovi library as vijMR. Sorry for the delay.

Vincent

**Comment by mhmmdbekci** [comment]
Hello, is it still available? I couldn't find it in the Jamovi library.

**Comment by jonathon-love** [comment]
are you using the 2.4 or 2.5?

**Comment by mhmmdbekci** [comment]
It was 2.3. Updated and find it in library. Thanks for the reminder Jonathon. Thanks for the module Vincent.
