### ISSUE TITLE
Requests: Example file

### ISSUE THREAD

**Issue by hyunsooseol** [vjalby/multipleresponse#5]
Hi

Thanks for providing Multiple Response Crosstabs option. 

This is GREAT !.  and I need  how to use it.

Could you attach example file here? or provide brief description for it.

Thanks in advance

Kind Regards
Seol
![image](https://github.com/user-attachments/assets/cb85582d-62b5-4fd2-8243-3339551ed3bd)

**Comment by vjalby** [comment]
@hyunsooseol 
I updated the sample files creditcards.omv with comments. I hope it will help you.

**Comment by hyunsooseol** [comment]
Hi [vjalby](https://github.com/vjalby)

Thanks for your comments.  I can not find crosstabs analysis on WIN 10 and jamovi 2.6.2. Coud you check it for me? Thanks always.

Kind Regards
Seol

**Comment by vjalby** [comment]
Hi @hyunsooseol 

Version 2.0 (with crosstabs) is not yet available in Jamovi Library (it will next monday). The jmo file available here is only for "Silicon Mac". I'm not sure I can build win10 module from my mac...
